---
- hosts: local
  become: true
  tasks:

  - name: Check current docker-compose version
    command: docker-compose --version
    register: docker_compose_current_version
    changed_when: false
    failed_when: false
  
  - name: Echo docker-compose current
    debug:
      msg: "Docker-Compose current version: {{docker_compose_current_version}}"
      

  - name: "Install docker-compose from apt"
    apt:
      name: docker-compose
      state: present
      update_cache: yes
    tags:
    - docker
